#=========================================================================
# TravisCI Setup
#=========================================================================

#------------------------------------------------------------------------
# language and build matrix
#------------------------------------------------------------------------

dist: xenial
language: python

python:
 - "3.7.7"

env:
 - CONFIG="-v --tb=short"

#------------------------------------------------------------------------
# install dependencies
#------------------------------------------------------------------------

install:

 # Install packages
 - sudo apt-get install -y graphviz

 # Install PyMTL3
 - pip install git+https://github.com/cornell-brg/pymtl3.git@76e1ef87b2d7b6202abebea5b507398505910948#egg=pymtl3
 - pip list

#------------------------------------------------------------------------
# test runner
#------------------------------------------------------------------------

script:
 - mkdir -p build
 - cd build
 - py.test ../ $CONFIG

#-------------------------------------------------------------------------
# after success
#-------------------------------------------------------------------------
